### ISSUE TITLE
Move example deployed app from Heroku

### ISSUE THREAD

**Issue by duffn** [ruby-grape/grape-on-rack#45]
Since Heroku’s free tier is no longer (https://blog.heroku.com/next-chapter), the example deployed app should be moved to fly.io or something similar. Alternatively, don’t deploy an example app at all and simply remove it from the README.

**Comment by dblock** [comment]
I say we remove it, but also happy if someone else wanted to take on deploying, maybe you @duffn ?

**Comment by duffn** [comment]
I'd go with removing it. It's just a thing to maintain and probably doesn't get used often. Users can easily spin it up locally if they like.
